# Generated by Django 2.2.16 on 2022-03-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20220318_1620'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='follow_unque',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'following'), name='unique_following'),
        ),
    ]
